// Generated by CoffeeScript 1.8.0
(function() {
  var Code128Overlay, blockDisplayTimeMS, blockHeight, blockWidth, maxBlocksAtOnce;

  blockWidth = 32;

  blockHeight = 32;

  maxBlocksAtOnce = 4;

  blockDisplayTimeMS = 300;

  Code128Overlay = (function() {
    function Code128Overlay(options) {
      this.div = options.targetDiv;
      this.value = options.value;
      this.calcCode();
      this.init();
      this.run();
    }

    Code128Overlay.prototype.calcCode = function() {
      var barcode;
      barcode = new Code123C(this.value);
      return this.blocks = barcode.trueFalse();
    };

    Code128Overlay.prototype.init = function() {
      var size;
      this.startBlock = 0;
      this.canvas = document.createElement('canvas');
      this.div = document.getElementById(id);
      this.canvas.id = "Code128Overlay";
      size = blockWidth * maxBlocksAtOnce;
      this.canvas.width = size;
      this.canvas.height = size;
      this.canvas.style.zIndex = 8;
      this.canvas.style.position = "absolute";
      this.canvas.style.border = "none";
      return this.div.appendChild(canvas);
    };

    Code128Overlay.prototype.drawBlock = function(isOn, position) {
      var color, ctx;
      ctx = this.canvas.getContext('2d');
      if (isOn) {
        color = 'black';
      } else {
        color = 'white';
      }
      ctx.setFillStyle(color);
      return ctx.fillRect(pos * blockWidth, 0, (pos + 1) * blockWidth, blockHeight);
    };

    Code128Overlay.prototype.update = function() {
      var i, index, _i, _ref;
      for (i = _i = 0, _ref = this.maxBlocksAtOnce; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        index = this.startBlock + i;
        if (index < this.blocks.length) {
          this.drawBlock(this.blocks[index], i);
        }
      }
      this.startBlock += this.maxBlocksAtOnce;
      if (this.startBlock >= this.blocks.length) {
        return this.startBlock = 0;
      }
    };

    Code128Overlay.prototype.run = function() {
      return this.int = setInterval(this.update, blockDisplayTimeMS);
    };

    return Code128Overlay;

  })();

}).call(this);
