// Generated by CoffeeScript 1.8.0
(function() {
  var button;

  button = document.getElementById('go');

  button.addEventListener('click', function() {
    var barcodeDemo;
    return barcodeDemo = new Code128Overlay({
      targetDiv: 'dispcode',
      value: '02312'
    });
  });

}).call(this);
