// Generated by CoffeeScript 1.8.0
(function() {
  var barcodeDemo, button, dbg;

  dbg = '';

  window.debug = function(msg) {
    dbg = msg + '<br>' + dbg;
    return document.getElementById('msg').innerHTML = dbg;
  };

  window.onerror = function(err) {
    return debug(err);
  };

  button = document.getElementById('go');

  barcodeDemo = null;

  button.addEventListener('click', function() {
    var val;
    if (barcodeDemo != null) {
      barcodeDemo.stop();
    }
    val = document.getElementById('val').value;
    return barcodeDemo = new Code128Overlay({
      targetDiv: 'dispcode',
      value: val
    });
  });

}).call(this);
